# Generated by Django 5.2.3 on 2025-06-29 16:44

import RTeam_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='entrenadores/')),
                ('tipo', models.CharField(choices=[('ENTRENADOR', 'Entrenador'), ('DELEGADO', 'Delegado'), ('ENTRENADOR_PRACTICAS', 'Entrenador en Prácticas')], default='PRINCIPAL', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('goles', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveIntegerField(default=0)),
                ('tarjetas_amarillas', models.PositiveIntegerField(default=0)),
                ('tarjetas_rojas', models.PositiveIntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('dorsal', models.PositiveIntegerField(default=0)),
                ('posicion', models.CharField(choices=[('PORTERO', 'Portero'), ('CIERRE', 'Cierre'), ('ALA', 'Ala'), ('PIVOT', 'Pívot')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', RTeam_app.models.TemporadaField(help_text='Formato: YYYY/YYYY (ej: 2024/2025)', max_length=9)),
                ('activa', models.BooleanField(default=False, help_text='Indica si es la temporada actual')),
            ],
        ),
        migrations.CreateModel(
            name='EntrenadorEquipoTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incorporacion', models.DateField(auto_now_add=True)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('entrenadores', models.ManyToManyField(related_name='equipos', through='RTeam_app.EntrenadorEquipoTemporada', to='RTeam_app.entrenador')),
            ],
        ),
        migrations.AddField(
            model_name='entrenadorequipotemporada',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.equipo'),
        ),
        migrations.CreateModel(
            name='EquipoLigaTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incorporacion', models.DateField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorEquipoTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal_en_temporada', models.PositiveIntegerField(default=0)),
                ('fecha_incorporacion', models.DateField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.temporada')),
            ],
            options={
                'unique_together': {('jugador', 'equipo', 'temporada')},
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(related_name='equipos', through='RTeam_app.JugadorEquipoTemporada', to='RTeam_app.jugador'),
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('equipos', models.ManyToManyField(related_name='ligas', through='RTeam_app.EquipoLigaTemporada', to='RTeam_app.equipo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.temporada')),
            ],
            options={
                'unique_together': {('nombre', 'temporada')},
            },
        ),
        migrations.AddField(
            model_name='equipoligatemporada',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.liga'),
        ),
        migrations.AddField(
            model_name='entrenadorequipotemporada',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.temporada'),
        ),
        migrations.AlterUniqueTogether(
            name='equipoligatemporada',
            unique_together={('equipo', 'liga')},
        ),
        migrations.AlterUniqueTogether(
            name='entrenadorequipotemporada',
            unique_together={('entrenador', 'equipo', 'temporada')},
        ),
    ]
