# Generated by Django 5.2.3 on 2025-06-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RTeam_app', '0002_rename_dorsal_en_temporada_jugadorequipotemporada_dorsal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrenador',
            options={'verbose_name_plural': 'Entrenadores'},
        ),
        migrations.AlterModelOptions(
            name='entrenadorequipotemporada',
            options={'verbose_name': 'Entrenador en Equipo por Temporada', 'verbose_name_plural': 'Entrenadores en Equipos por Temporada'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='equipoligatemporada',
            options={'verbose_name': 'Equipo en Liga', 'verbose_name_plural': 'Equipos en Ligas'},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='jugadorequipotemporada',
            options={'verbose_name': 'Jugador en Equipo por Temporada', 'verbose_name_plural': 'Jugadores en Equipos por Temporada'},
        ),
        migrations.AlterModelOptions(
            name='liga',
            options={'verbose_name_plural': 'Ligas'},
        ),
        migrations.AlterModelOptions(
            name='temporada',
            options={'verbose_name_plural': 'Temporadas'},
        ),
    ]
