# Generated by Django 5.2.3 on 2025-07-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTeam_app', '0003_alter_entrenador_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenador',
            name='tipo',
        ),
        migrations.AddField(
            model_name='entrenadorequipotemporada',
            name='tipo',
            field=models.CharField(choices=[('ENTRENADOR', 'Entrenador'), ('DELEGADO', 'Delegado'), ('ENTRENADOR_PRACTICAS', 'Entrenador en Prácticas')], default='PRINCIPAL', max_length=20),
        ),
    ]
