# Generated by Django 5.2.3 on 2025-07-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTeam_app', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('JUGADOR', 'Jugador'), ('INVITADO', 'Invitado')], default='INVITADO', max_length=20),
        ),
    ]
