# Generated by Django 5.2.3 on 2025-07-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTeam_app', '0008_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
