# Generated by Django 5.2.3 on 2025-07-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTeam_app', '0010_alter_entrenador_foto_alter_equipo_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='entrenador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='RTeam_app.entrenador'),
        ),
        migrations.AddField(
            model_name='profile',
            name='jugador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='RTeam_app.jugador'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('JUGADOR', 'Jugador'), ('ENTRENADOR', 'Entrenador'), ('INVITADO', 'Invitado')], default='INVITADO', max_length=20),
        ),
    ]
