# Generated by Django 5.2.3 on 2025-07-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTeam_app', '0011_profile_entrenador_profile_jugador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenadorequipotemporada',
            name='tipo',
            field=models.CharField(choices=[('ENTRENADOR', 'Entrenador'), ('DELEGADO', 'Delegado'), ('ENTRENADOR_PRACTICAS', 'Entrenador en Prácticas')], default='ENTRENADOR', max_length=20),
        ),
    ]
