# Generated by Django 5.2.3 on 2025-07-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTeam_app', '0013_campo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('jornada', models.PositiveIntegerField()),
                ('goles_local', models.PositiveIntegerField(default=0)),
                ('goles_visitante', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('FINALIZADO', 'Finalizado'), ('SUSPENDIDO', 'Suspendido')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.campo')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_locales', to='RTeam_app.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitantes', to='RTeam_app.equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.liga')),
            ],
            options={
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='EventoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('GOL', 'Gol'), ('ASISTENCIA', 'Asistencia'), ('TARJETA_AMARILLA', 'Tarjeta Amarilla'), ('TARJETA_ROJA', 'Tarjeta Roja')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('asistidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_partido', to='RTeam_app.jugador')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_partido', to='RTeam_app.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.partido')),
            ],
            options={
                'verbose_name_plural': 'Eventos de Partido',
            },
        ),
        migrations.CreateModel(
            name='ConvocatoriaPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CONVOCADO', 'Convocado'), ('NO_CONVOCADO', 'No Convocado'), ('LESIONADO', 'Lesionado'), ('SANCIONADO', 'Sancionado')], default='CONVOCADO', max_length=20)),
                ('dorsal', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTeam_app.partido')),
            ],
            options={
                'verbose_name': 'Convocatoria a Partido',
                'verbose_name_plural': 'Convocatorias a Partido',
                'unique_together': {('partido', 'jugador')},
            },
        ),
    ]
