# Generated by Django 5.2.3 on 2025-08-01 16:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTeam_app', '0015_equipo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='color',
            field=models.CharField(blank=True, help_text='Color principal de la liga', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='liga',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
