# Generated by Django 5.2.3 on 2025-08-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTeam_app', '0016_liga_color_liga_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='destacada',
            field=models.BooleanField(default=False, help_text='Si se marca, esta liga aparecerá por defecto'),
        ),
    ]
