# Generated by Django 5.2.3 on 2025-08-08 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTeam_app', '0017_liga_destacada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventopartido',
            options={'ordering': ['fecha_creacion'], 'verbose_name_plural': 'Eventos de Partido'},
        ),
        migrations.AddField(
            model_name='eventopartido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
