from django.urls import path
from RTeam_app import views

urlpatterns = [
    path('', views.sign_in, name='sign_in'),
    path('sign-out/', views.sign_out, name='sign_out'),
    path('auth-receiver/', views.auth_receiver, name='auth_receiver'),
    path('google-auth/', views.AuthGoogle.as_view(), name='google_auth'),

    path('inicio/', views.index, name='index'),
    path('equipos_menu/', views.equipos_menu, name='equipos_menu'),
    path('temporadas/', views.TemporadaListView.as_view(), name='temporada_list'),
    path('temporadas/crear/', views.TemporadaCreateView.as_view(), name='temporada_create'),
    path('temporadas/<int:pk>/', views.TemporadaDetailView.as_view(), name='temporada_detail'),
    path('temporadas/<int:pk>/editar/', views.TemporadaUpdateView.as_view(), name='temporada_update'),
    path('temporadas/<int:pk>/eliminar/', views.TemporadaDeleteView.as_view(), name='temporada_delete'),
    path('ligas/', views.LigaListView.as_view(), name='liga_list'),
    path('ligas/crear/', views.LigaCreateView.as_view(), name='liga_create'),
    path('ligas/<int:pk>/', views.LigaDetailView.as_view(), name='liga_detail'),
    path('ligas/<int:pk>/editar/', views.LigaUpdateView.as_view(), name='liga_update'),
    path('ligas/<int:pk>/eliminar/', views.LigaDeleteView.as_view(), name='liga_delete'),
    path('ligas/<int:liga_id>/agregar_equipo/', views.EquipoLigaCreateView.as_view(), name='equipo_liga_create'),
    # En urls.py
    path('ligas/equipo/<int:pk>/eliminar/', views.EquipoLigaDeleteView.as_view(), name='equipo_en_liga_delete'),
    path('equipos/', views.EquipoListView.as_view(), name='equipo_list'),
    path('equipos/crear/', views.EquipoCreateView.as_view(), name='equipo_create'),
    path('equipos/<int:pk>/', views.EquipoDetailView.as_view(), name='equipo_detail'),
    path('equipos/<int:pk>/editar/', views.EquipoUpdateView.as_view(), name='equipo_update'),
    path('equipos/<int:pk>/eliminar/', views.EquipoDeleteView.as_view(), name='equipo_delete'),
    path('equipos/<int:equipo_id>/agregar_jugador/', views.JugadorEquipoTemporadaCreateView.as_view(),
         name='jugador_equipo_create'),
    path('equipos/<int:equipo_id>/jugadores/<int:jugador_id>/eliminar/',
         views.JugadorEquipoTemporadaDeleteView.as_view(),
         name='jugador_en_equipo_delete'),

    path('equipos/<int:equipo_id>/agregar_entrenador/', views.EntrenadorEquipoTemporadaCreateView.as_view(),
         name='entrenador_equipo_create'),
    path('equipos/<int:equipo_id>/entrenadores/<int:entrenador_id>/eliminar/',
         views.EntrenadorEquipoTemporadaDeleteView.as_view(),
         name='entrenador_en_equipo_delete'),
    path('jugadores/', views.JugadorListView.as_view(), name='jugador_list'),
    path('jugadores/<int:pk>/', views.JugadorDetailView.as_view(), name='jugador_detail'),
    path('jugadores/crear/', views.JugadorCreateView.as_view(), name='jugador_create'),
    path('jugadores/<int:pk>/editar/', views.JugadorUpdateView.as_view(), name='jugador_update'),
    path('jugadores/<int:pk>/eliminar/', views.JugadorDeleteView.as_view(), name='jugador_delete'),
    path('entrenadores/', views.EntrenadorListView.as_view(), name='entrenador_list'),
    path('entrenadores/<int:pk>/', views.EntrenadorDetailView.as_view(), name='entrenador_detail'),
    path('entrenadores/crear/', views.EntrenadorCreateView.as_view(), name='entrenador_create'),
    path('entrenadores/<int:pk>/editar/', views.EntrenadorUpdateView.as_view(), name='entrenador_update'),
    path('entrenadores/<int:pk>/eliminar/', views.EntrenadorDeleteView.as_view(), name='entrenador_delete'),
    path('serviceworker.js', views.service_worker, name='serviceworker'),
    path('usuarios/', views.UsuarioListView.as_view(), name='usuario_list'),
    path('usuarios/<int:pk>/editar/', views.UsuarioUpdateView.as_view(), name='usuario_update'),
    path('usuarios/<int:pk>/eliminar/', views.UsuarioDeleteView.as_view(), name='usuario_delete'),
]
